"use client"

import { useState } from 'react'
import Link from 'next/link'
import { Download, Play, Loader2, Check, ExternalLink, Trash2 } from 'lucide-react'
import { generateVideoMaterialsAction, flagSignalAction } from '@/app/actions'

interface FlaggedSignalCardProps {
    signal: {
        id: string;
        hash: string;
        headline: string;
        source: string;
        sources?: { name: string };
        created_at: string;
        summary?: string;
        ai_summary?: string;
    }
}

export default function FlaggedSignalCard({ signal }: FlaggedSignalCardProps) {
    const [loading, setLoading] = useState(false);
    const [materials, setMaterials] = useState<any>(null);
    const [hasExported, setHasExported] = useState(false);

    const handleGenerateAndExport = async () => {
        setLoading(true);

        // Generate materials
        const result = await generateVideoMaterialsAction(signal.id);

        if (result.success && result.materials) {
            setMaterials(result.materials);
            downloadMarkdown(result.materials);
            setHasExported(true);
        } else {
            alert("Failed to generate materials: " + result.error);
        }

        setLoading(false);
    };

    const downloadMarkdown = (mats: any) => {
        const now = new Date();
        const dateStr = now.toISOString().split('T')[0];
        const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
        const slug = signal.hash || signal.id;

        const markdown = `# Video Materials: ${signal.headline}

**Generated:** ${dateStr} ${timeStr}  
**Signal ID:** ${slug}  

---

## 60-Second Video Script

${mats.script || 'No script generated.'}

---

## Key Quotes

${mats.quotes?.length > 0
                ? mats.quotes.map((q: any, i: number) => `**Quote ${i + 1}:**\n"${q.text}"\n— **${q.attribution}**\n`).join('\n')
                : 'No quotes extracted.'
            }

---

## Contradictions Detected

${mats.contradictions?.length > 0
                ? mats.contradictions.map((c: any, i: number) =>
                    `**Contradiction ${i + 1}:**\n- **Claim:** ${c.claim}\n- **Counter:** ${c.counter}\n- **Evidence:** ${c.evidence}\n`
                ).join('\n')
                : 'No contradictions detected.'
            }

---

## Suggested Angles

${mats.angles?.length > 0
                ? mats.angles.map((a: string, i: number) => `${i + 1}. **${a}**`).join('\n')
                : 'No angles suggested.'
            }

---

*Generated by CANOPTICON • canopticon.ca*
`;

        const filename = `${dateStr}_${slug.substring(0, 20)}_materials.md`;
        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleReExport = () => {
        if (materials) {
            downloadMarkdown(materials);
        }
    };

    return (
        <div className="flex items-center justify-between p-4 rounded-xl bg-black/40 border border-white/5 hover:border-purple-500/30 transition-colors group">
            <div className="flex-1 min-w-0 mr-4">
                <h3 className="font-medium truncate group-hover:text-purple-300 transition-colors">{signal.headline}</h3>
                <p className="text-sm text-gray-500">
                    {signal.sources?.name || signal.source} • {new Date(signal.created_at).toLocaleTimeString()}
                </p>
            </div>

            <div className="flex gap-2">
                {hasExported ? (
                    <>
                        <button
                            onClick={handleReExport}
                            className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-green-500/10 text-green-400 rounded-lg border border-green-500/20"
                        >
                            <Check className="w-3 h-3" /> Exported
                        </button>
                        <button
                            onClick={handleReExport}
                            className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-white/5 hover:bg-white/10 rounded-lg transition-colors"
                        >
                            <Download className="w-3 h-3" /> Re-download
                        </button>
                    </>
                ) : (
                    <button
                        onClick={handleGenerateAndExport}
                        disabled={loading}
                        className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 rounded-lg border border-purple-500/20 transition-colors disabled:opacity-50"
                    >
                        {loading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
                        {loading ? 'Generating...' : 'Export Materials'}
                    </button>
                )}

                <Link
                    href={`/admin/content/${signal.id}/edit`}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 rounded-lg border border-cyan-500/20 transition-colors"
                >
                    <ExternalLink className="w-3 h-3" /> Edit
                </Link>
                <button
                    onClick={async () => {
                        if (confirm("Unflag this item?")) {
                            await flagSignalAction(signal.id);
                            window.location.reload();
                        }
                    }}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium text-gray-500 hover:text-red-400 rounded-lg transition-colors"
                >
                    <Trash2 className="w-3 h-3" /> Remove
                </button>
            </div>
        </div>
    )
}
