"use client"

import { useState } from 'react'
import { Video, Loader2, FileDown, Check, Download } from 'lucide-react'
import { generateVideoMaterialsAction } from '@/app/actions'

interface VideoGeneratorProps {
    signalId: string;
    signalHeadline: string;
    signalHash: string;
    hasExistingMaterials?: boolean;
}

export default function VideoGenerator({ signalId, signalHeadline, signalHash, hasExistingMaterials = false }: VideoGeneratorProps) {
    const [loading, setLoading] = useState(false);
    const [success, setSuccess] = useState(hasExistingMaterials);
    const [materials, setMaterials] = useState<any>(null);

    const handleGenerate = async () => {
        setLoading(true);
        const result = await generateVideoMaterialsAction(signalId);
        setLoading(false);

        if (result.success && result.materials) {
            setSuccess(true);
            setMaterials(result.materials);
        } else {
            alert("Generation failed: " + result.error);
        }
    };

    const handleDownload = () => {
        if (!materials) {
            alert("No materials available. Generate first.");
            return;
        }

        // Build markdown per spec format
        const now = new Date();
        const dateStr = now.toISOString().split('T')[0];
        const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
        const slug = signalHash || signalId;

        const markdown = `# Video Materials: ${signalHeadline}

**Generated:** ${dateStr} ${timeStr}  
**Signal ID:** ${slug}  

---

## 60-Second Video Script

${materials.script || 'No script generated.'}

---

## Key Quotes

${materials.quotes?.length > 0
                ? materials.quotes.map((q: any, i: number) => `**Quote ${i + 1}:**\n"${q.text}"\n— **${q.attribution}**\n`).join('\n')
                : 'No quotes extracted.'
            }

---

## Contradictions Detected

${materials.contradictions?.length > 0
                ? materials.contradictions.map((c: any, i: number) =>
                    `**Contradiction ${i + 1}:**\n- **Claim:** ${c.claim}\n- **Counter:** ${c.counter}\n- **Evidence:** ${c.evidence}\n`
                ).join('\n')
                : 'No contradictions detected.'
            }

---

## Suggested Angles

${materials.angles?.length > 0
                ? materials.angles.map((a: string, i: number) => `${i + 1}. **${a}**`).join('\n')
                : 'No angles suggested.'
            }

---

*Generated by CANOPTICON • canopticon.ca*
`;

        // Create and download file
        const filename = `${dateStr}_${slug.substring(0, 20)}_materials.md`;
        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (success) {
        return (
            <div className="flex gap-2">
                <button className="flex items-center gap-2 px-3 py-1.5 bg-green-500/10 text-green-400 rounded-lg text-xs font-medium border border-green-500/20 cursor-default">
                    <Check className="w-3 h-3" /> Ready
                </button>
                <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-3 py-1.5 bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 rounded-lg text-xs font-medium border border-purple-500/20 transition-colors"
                >
                    <Download className="w-3 h-3" /> Download .md
                </button>
            </div>
        )
    }

    return (
        <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 rounded-lg text-xs font-bold border border-purple-500/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed">
            {loading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Video className="w-3 h-3" />}
            {loading ? "Generating..." : "Generate Prep"}
        </button>
    )
}
