import { Signal, IntakeLog } from '@/types'

export const mockSignals: Signal[] = [
  {
    id: '1',
    slug: 'signal-alpha-001',
    title: 'Alpha Signal Detected',
    source: 'Sensor Array 7',
    timestamp: new Date().toISOString(),
    priority: 'high',
    status: 'processing',
    content: 'Anomalous energy signature detected in sector 7-G. Pattern matches known threat profiles.',
    metadata: {
      coordinates: { x: 127, y: 89, z: 45 },
      intensity: 8.7,
    },
  },
  {
    id: '2',
    slug: 'signal-beta-042',
    title: 'Beta Transmission Intercepted',
    source: 'Deep Space Relay',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    priority: 'critical',
    status: 'pending',
    content: 'Encrypted transmission intercepted from unknown origin. Decryption in progress.',
    metadata: {
      frequency: '142.8 MHz',
      encryption: 'AES-256',
    },
  },
  {
    id: '3',
    slug: 'signal-gamma-789',
    title: 'Gamma Wave Anomaly',
    source: 'Quantum Scanner',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    priority: 'medium',
    status: 'resolved',
    content: 'Temporary quantum fluctuation detected. System stability confirmed.',
    metadata: {
      duration: '2.3 seconds',
      amplitude: 0.45,
    },
  },
  {
    id: '4',
    slug: 'signal-delta-333',
    title: 'Delta Pattern Recognition',
    source: 'AI Analysis Engine',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    priority: 'low',
    status: 'archived',
    content: 'Routine pattern match identified. No action required.',
    metadata: {
      confidence: 0.92,
      pattern: 'Type-7 Standard',
    },
  },
]

export const mockIntakeLogs: IntakeLog[] = [
  {
    id: 'log-1',
    timestamp: new Date().toISOString(),
    source: 'Sensor Array 7',
    signalId: '1',
    action: 'Signal Received',
    status: 'success',
    details: 'Signal successfully ingested into system',
  },
  {
    id: 'log-2',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    source: 'Deep Space Relay',
    signalId: '2',
    action: 'Transmission Intercepted',
    status: 'success',
    details: 'Encrypted payload captured and queued for analysis',
  },
  {
    id: 'log-3',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    source: 'Quantum Scanner',
    signalId: '3',
    action: 'Anomaly Detected',
    status: 'success',
    details: 'Quantum fluctuation logged and analyzed',
  },
  {
    id: 'log-4',
    timestamp: new Date(Date.now() - 5400000).toISOString(),
    source: 'AI Analysis Engine',
    signalId: '4',
    action: 'Pattern Match',
    status: 'success',
    details: 'Routine pattern identified and archived',
  },
  {
    id: 'log-5',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    source: 'Network Gateway',
    signalId: '5',
    action: 'Connection Attempt',
    status: 'failed',
    details: 'Failed to establish connection with remote sensor',
  },
]
