'use client'

import { useState, useEffect } from 'react'

/**
 * Article Type
 * Represents a generated article from pipeline execution
 *
 * Fields:
 * - headline: Title of the article
 * - summary: Short description
 * - content: Full article body (generated by writing pipeline)
 * - topics: Tags/categories
 * - isDraft: Whether article is still being worked on
 */
interface Article {
    id: string
    slug: string
    headline: string
    summary: string
    content: string | null
    topics: string[]
    isDraft: boolean
    createdAt: string
}

/**
 * Articles Admin Page
 *
 * Purpose: View all generated articles and their full content
 * Users can:
 * - See list of all articles
 * - Click to view full article content
 * - Verify prompt output quality
 * - Check article metadata (status, creation date, topics)
 *
 * Data Flow:
 * 1. Load all articles from /api/admin/articles
 * 2. Display as list with headlines and summaries
 * 3. When clicked, fetch full article details from /api/admin/articles/[id]
 * 4. Show detail view with full content
 */
export default function ArticlesPage() {
    const [articles, setArticles] = useState<Article[]>([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)
    const [selectedArticleId, setSelectedArticleId] = useState<string | null>(null)
    const [selectedArticle, setSelectedArticle] = useState<Article | null>(null)
    const [loadingDetail, setLoadingDetail] = useState(false)
    const [detailError, setDetailError] = useState<string | null>(null)

    useEffect(() => {
        loadArticles()
    }, [])

    /**
     * Load all articles from the database
     * Shows loading state and error handling
     */
    async function loadArticles() {
        try {
            setLoading(true)
            setError(null)

            console.log('[articles] Loading all articles...')

            const res = await fetch('/api/admin/articles')

            if (!res.ok) {
                throw new Error(`Failed to load articles: ${res.status}`)
            }

            const data = await res.json()
            setArticles(data.articles || [])

            console.log(`[articles] Loaded ${data.articles?.length || 0} articles`)
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : String(err)
            setError(`❌ Error loading articles: ${errorMsg}`)
            console.error('[articles] Load error:', err)
        } finally {
            setLoading(false)
        }
    }

    /**
     * Load full details for a single article
     * Triggered when user clicks on an article
     */
    async function loadArticleDetail(articleId: string) {
        try {
            setLoadingDetail(true)
            setDetailError(null)

            console.log(`[articles] Loading detail for article (id="${articleId}")`)

            const res = await fetch(`/api/admin/articles/${articleId}`)

            if (!res.ok) {
                throw new Error(`Failed to load article: ${res.status}`)
            }

            const data = await res.json()
            setSelectedArticle(data.article)

            console.log(`[articles] Detail loaded (headline="${data.article.headline}")`)
        } catch (err) {
            const errorMsg = err instanceof Error ? err.message : String(err)
            setDetailError(`❌ Error loading article details: ${errorMsg}`)
            console.error('[articles] Detail load error:', err)
        } finally {
            setLoadingDetail(false)
        }
    }

    // ========== RENDER ==========

    if (loading) {
        return (
            <div className="max-w-4xl">
                <div className="text-center py-12 text-slate-400">
                    🔄 Loading articles...
                </div>
            </div>
        )
    }

    // Detail view (when article is selected)
    if (selectedArticleId && selectedArticle) {
        return (
            <div className="max-w-4xl">
                {/* Back button */}
                <button
                    onClick={() => {
                        setSelectedArticleId(null)
                        setSelectedArticle(null)
                        setDetailError(null)
                    }}
                    className="mb-6 text-primary-400 hover:text-primary-300 text-sm font-medium"
                >
                    ← Back to Articles
                </button>

                {/* Error message */}
                {detailError && (
                    <div className="mb-6 p-4 bg-red-500/20 border border-red-500/50 rounded text-red-300 whitespace-pre-wrap">
                        {detailError}
                    </div>
                )}

                {/* Loading state */}
                {loadingDetail && (
                    <div className="text-center py-12 text-slate-400">
                        🔄 Loading article details...
                    </div>
                )}

                {/* Article detail */}
                {!loadingDetail && selectedArticle && (
                    <div>
                        {/* Header */}
                        <div className="mb-6">
                            <div className="flex items-start justify-between mb-4">
                                <div>
                                    <h1 className="text-4xl font-bold text-white mb-3">
                                        {selectedArticle.headline}
                                    </h1>
                                    <span
                                        className={`inline-block px-3 py-1 rounded text-sm font-medium ${
                                            selectedArticle.isDraft
                                                ? 'bg-yellow-500/20 text-yellow-400'
                                                : 'bg-green-500/20 text-green-400'
                                        }`}
                                    >
                                        {selectedArticle.isDraft ? 'Draft' : 'Published'}
                                    </span>
                                </div>
                            </div>

                            {/* Metadata */}
                            <div className="space-y-2 text-sm text-slate-400 mb-6">
                                <div>
                                    <span className="font-medium text-slate-300">Created:</span>{' '}
                                    {new Date(selectedArticle.createdAt).toLocaleString()}
                                </div>
                                <div>
                                    <span className="font-medium text-slate-300">Slug:</span>{' '}
                                    <span className="font-mono text-slate-300">
                                        {selectedArticle.slug}
                                    </span>
                                </div>
                                <div>
                                    <span className="font-medium text-slate-300">ID:</span>{' '}
                                    <span className="font-mono text-slate-300 text-xs">
                                        {selectedArticle.id}
                                    </span>
                                </div>
                                {selectedArticle.topics && selectedArticle.topics.length > 0 && (
                                    <div>
                                        <span className="font-medium text-slate-300">Topics:</span>{' '}
                                        {selectedArticle.topics.join(', ')}
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Summary */}
                        <div className="mb-8 p-4 bg-blue-500/10 border border-blue-500/20 rounded">
                            <h3 className="font-bold text-blue-300 mb-2">Summary</h3>
                            <p className="text-slate-300">{selectedArticle.summary}</p>
                        </div>

                        {/* Content */}
                        {selectedArticle.content ? (
                            <div className="mb-8">
                                <h2 className="text-2xl font-bold text-white mb-4">
                                    Full Article
                                </h2>
                                <div className="prose prose-invert max-w-none">
                                    <p className="text-slate-200 leading-relaxed whitespace-pre-wrap">
                                        {selectedArticle.content}
                                    </p>
                                </div>
                            </div>
                        ) : (
                            <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded text-yellow-300">
                                ⚠️ No content generated yet. Run the writing pipeline to generate
                                full article content.
                            </div>
                        )}
                    </div>
                )}
            </div>
        )
    }

    // List view
    return (
        <div className="max-w-4xl">
            {/* Header */}
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-white mb-2">Articles</h1>
                <p className="text-slate-400">
                    View all generated articles from pipeline runs. Click on an article to see
                    full content.
                </p>
            </div>

            {/* Error message */}
            {error && (
                <div className="mb-6 p-4 bg-red-500/20 border border-red-500/50 rounded text-red-300 whitespace-pre-wrap">
                    {error}
                </div>
            )}

            {/* Articles list */}
            {articles.length === 0 ? (
                <div className="text-center py-12 text-slate-500">
                    No articles yet. Run a pipeline to generate one.
                </div>
            ) : (
                <div className="space-y-4">
                    {articles.map((article) => (
                        <button
                            key={article.id}
                            onClick={() => {
                                setSelectedArticleId(article.id)
                                loadArticleDetail(article.id)
                            }}
                            className="w-full text-left p-6 bg-white/5 rounded-lg border border-white/10 hover:bg-white/10 hover:border-white/20 transition-colors"
                        >
                            <div className="flex items-start justify-between mb-3">
                                <div className="flex-1">
                                    <h2 className="text-xl font-bold text-white hover:text-primary-400 transition-colors">
                                        {article.headline}
                                    </h2>
                                    <p className="text-sm text-slate-400 mt-2">
                                        {article.summary}
                                    </p>
                                </div>
                                <span
                                    className={`px-3 py-1 rounded text-sm font-medium whitespace-nowrap ml-4 ${
                                        article.isDraft
                                            ? 'bg-yellow-500/20 text-yellow-400'
                                            : 'bg-green-500/20 text-green-400'
                                    }`}
                                >
                                    {article.isDraft ? 'Draft' : 'Published'}
                                </span>
                            </div>

                            <div className="flex items-center gap-4 text-xs text-slate-500 mb-2">
                                <span>
                                    {new Date(article.createdAt).toLocaleDateString()}
                                </span>
                                {article.topics && article.topics.length > 0 && (
                                    <span className="text-slate-400">
                                        {article.topics.join(', ')}
                                    </span>
                                )}
                            </div>

                            <div className="text-xs text-slate-500 font-mono">
                                {article.content
                                    ? `✅ ${article.content.length} characters`
                                    : '⚠️ No content yet'}
                            </div>
                        </button>
                    ))}
                </div>
            )}
        </div>
    )
}
